# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  rn: react-native-community/react-native@5.1.0
  
jobs: 
  checkout_code:
    executor:
      name: rn/linux_js
      node_version: '12'
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .
    
  appcenter_android_release:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      # - run:
      #     command: exec git config user.email "danbfjr@gmail.com" 
      #     name: Setting GitHub Identity...
      - run:
          command: exec npm version minor && git push https://$GITHUB_TOKEN@github.com/leeferfeefer/readgooder.git
          name: Updating Version...
      - run:
          command: exec appcenter login --token $APPCENTER_TOKEN && appcenter distribute release --app danbfjr/readgooder --file ./android/app/build/outputs/apk/release/app-release.apk --group Internal
          name: Deploy to Appcenter...
workflows:
  main:
    jobs:
      - checkout_code
      - rn/android_build:
          build_type: release
          name: build_android_release
          project_path: android
          requires: 
            - checkout_code
      - appcenter_android_release:
          requires:
            - build_android_release
            